version: "3.9"

services:
  api:
    container_name: ${APP_NAME}-go-server
    env_file:
      - ../.env
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"